# Generated by Django 3.1.5 on 2021-02-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffuer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Ad')),
                ('comment_content', models.CharField(max_length=500, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chauffuer',
            name='ChauffuerName',
            field=models.CharField(max_length=50, verbose_name='Plaka & Şöför Adı'),
        ),
        migrations.AlterField(
            model_name='chauffuer',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
    ]
