# Generated by Django 3.1.5 on 2021-02-03 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chauffuer', '0003_remove_comment_comment_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chauffuer',
        ),
    ]
