# Generated by Django 3.1.5 on 2021-02-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffuer', '0004_delete_chauffuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=500, null=True, verbose_name='Yorum'),
        ),
    ]
